services:

  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - ./firefly_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - "21100:8080"
    depends_on:
      - db
      
  db:
    image: mariadb:latest
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - ./firefly_db:/var/lib/mysql
      
  cron:
    #
    # Para que esto funcione, configure STATIC_CRON_TOKEN en su archivo .env o como una variable de entorno y reemplace "klI0JEC7TkDisfFuyjbRsIqATxmH5qRW" a continuación.
    # El STATIC_CRON_TOKEN debe tener *exactamente* 32 caracteres de longitud
    #
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/klI0JEC7TkDisfFuyjbRsIqATxmH5qRW;echo\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
   
